### ISSUE TITLE
Test case

### ISSUE THREAD

**Issue by FrancescoBaroneItaly** [alessandro1105/XXTEA_Arduino_Library#2]
Hello, I'm using library and during the tests I see this behaviour:

I'm trying to decrypt a previous crypted data :+1: 

This is the source data crypted with key 8877
whUl7NYiVXsAikqf

The decryption process dosen't finish succefully.

I tested this decryption from online tool or using a java library and finished succefully.
https://www.tools4noobs.com/online_tools/xxtea_decrypt/

So whUl7NYiVXsAikqf -->>DECRYPT with 8877 key -->>  nerated"

Could you reproduce the issue?

Thank's a lot!

Bye F.

**Comment by alessandro1105** [comment]
Hi Francesco,
sorry for the delay :)

I'm investigating the issue right now and i've found out that the problem presents itself only with some key/message associations.

If you change the key from "8877" to "5555", for example, the string will be encrypted correctly and,  If you encode the encrypted message with base64, the site you linked me decrypt the message smoothly.

I suspect that the problem is some kind of overflow in the encrypt/decrypt process and i'm on it right now.

The library has some other minor problems (i.e. it rely on the string you passed to the encrypt/decrypt method instead of using a buffer) due to a poorly implementation that i've made years ago. I'll fix these issues too in the next release, after solving the encrypt/decrypt problem.

I'll keep you updated.
Alessandro

**Comment by alessandro1105** [comment]
Hi,
I just finished fixing the bug you point out and in doing so I also added some features too (e.g. the possibility to store the output of the encrypt/decrypt methods to a buffer instead of rely on the input string)

The reality was that it wasn't really a bug but an expected behavior due to the null-terminated strings in c/c++.
I explain myself.

Some association key/message produce encrypted strings that have some null character in the middle of the string but that are not the null-terminator. This produces an "erroneous" behavior of all the string managing function of the c/c++ language, because they truncate the string to the first null character, thinking it's the null-terminator, but it's not.

To solve this issue the encrypt/decrypt methods return the exact number of characters of the encrypted/decrypted string and that it's the real string length.

This below it's an example code for Arduino IDE to use this library with the modifications I added. In the near future i will release a new version of the library with some examples. Stay tuned!

```
#include <XXTEA.h>
#include <Base64.h>

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);

  //setting up key
  XXTEA xxtea("8877", 4);

  //message to encrypt/decrypt
  char message[30] = "nerated\"";
  
  Serial.println("MESSAGE TO ENCRYPT");
  Serial.println("-----------------");
  Serial.println(message);
  Serial.println("-----------------\n");

  //encrypt message
  size_t len = xxtea.encrypt(message, strlen(message), message, sizeof(message));

  //buffer to store base64 encoded encrypted message
  char base64_buff[200];

  //encode message into base64
  base64_encode(base64_buff, message, len);

  Serial.println("MESSAGE ENCRYPTYED AND ENCODED BASE64");
  Serial.println("-----------------");
  Serial.println(base64_buff);
  Serial.println("-----------------\n");

  //decode base64 encoded message
  base64_decode(message, base64_buff, strlen(base64_buff));

  //decrypt message
  xxtea.decrypt(message, len, message, sizeof(message));

  Serial.println("MESSAGE DECRYPTED");
  Serial.println("-----------------");
  Serial.println(message);
  Serial.println("-----------------\n");
 
}

void loop() {
  // put your main code here, to run repeatedly:

}
```
P.S I used [this libray](https://github.com/adamvr/arduino-base64) for the base64 encoding/decoding part.
